<?xml version="1.0" encoding="utf-8"?>
<MODEL>
  <SAVED_IN_CULTURE>en-US</SAVED_IN_CULTURE>
  <MODEL_FILE_VERSION>4.2</MODEL_FILE_VERSION>
  <MODEL_VERSION MAJOR="26" MINOR="11" BUILD="0" PATCH="201" />
  <GLOBAL_DATA_KEY>00000000-0000-0000-0000-000000000000</GLOBAL_DATA_KEY>
  <MODEL_INFO>
    <OUTPUT_BUILD_FOLDER>C:\23.11\FT\MMAS\Release DLLs\</OUTPUT_BUILD_FOLDER>
    <PATH>C:\Moodys\cao-cl-mod-ft\MMAS\TPL\MMAS.tpl</PATH>
    <ID>6</ID>
    <CHECKINKEY>00000000-0000-0000-0000-000000000000</CHECKINKEY>
    <QAC>True</QAC>
    <CLASSHIDING>False</CLASSHIDING>
    <SPREADINGGUIDE>True</SPREADINGGUIDE>
    <SUPPORTSRATINGS>True</SUPPORTSRATINGS>
    <DISABLE_ST_PROJECTION>False</DISABLE_ST_PROJECTION>
    <DISABLE_LT_PROJECTION>False</DISABLE_LT_PROJECTION>
    <DISABLE_PEER_COMPARISON>False</DISABLE_PEER_COMPARISON>
    <DISABLE_CONSOLIDATIONS>False</DISABLE_CONSOLIDATIONS>
    <DEFAULTLANG>1</DEFAULTLANG>
    <STMTTYPE_ANNUAL_ID>ANNUAL</STMTTYPE_ANNUAL_ID>
    <STMTTYPE_YEARTODATE_ID>FY-TO-DATE</STMTTYPE_YEARTODATE_ID>
    <LANGUAGES>
      <LANG ID="1" />
      <LANG ID="3" />
      <LANG ID="9" />
      <LANG ID="11" />
      <LANG ID="12" />
      <LANG ID="13" />
      <LANG ID="16" />
    </LANGUAGES>
    <NAMES>
      <NAME ID="1">MMAS</NAME>
      <NAME ID="3">MMAS</NAME>
      <NAME ID="9">MMAS</NAME>
      <NAME ID="11">MMAS</NAME>
      <NAME ID="12">MMAS</NAME>
      <NAME ID="13">MMAS</NAME>
      <NAME ID="16">MMAS</NAME>
    </NAMES>
    <DESCRIPTIONS>
      <DESCRIPTION ID="1">General Business</DESCRIPTION>
      <DESCRIPTION ID="3">Modèle commercial général</DESCRIPTION>
      <DESCRIPTION ID="9">Administración empresarial general</DESCRIPTION>
      <DESCRIPTION ID="11">Negócios Gerais</DESCRIPTION>
      <DESCRIPTION ID="12">Plantilla financiera general</DESCRIPTION>
      <DESCRIPTION ID="13">ธุรกิจทั่วไป</DESCRIPTION>
      <DESCRIPTION ID="16">Algemene bedrijfsvoering</DESCRIPTION>
    </DESCRIPTIONS>
  </MODEL_INFO>
  <MODEL_ADDINS />
  <MACRO_GROUPINGS />
  <UNKNOWN_MODEL_PROPERTIES />
  <MODEL_CONFIG><![CDATA[]]></MODEL_CONFIG>
  <RC_MODELS />
  <STMT_CONSTANTS>
    <STMT_TYPE_STMT_CONST_ID>0</STMT_TYPE_STMT_CONST_ID>
    <ANALYST_STMT_CONST_ID>0</ANALYST_STMT_CONST_ID>
    <AUDIT_METHOD_STMT_CONST_ID>0</AUDIT_METHOD_STMT_CONST_ID>
  </STMT_CONSTANTS>
  <DIVISIONS />
  <ENTRY_METHODS />
  <TYPES />
  <FLOWS />
  <CLASSES />
  <CONSTANTS />
  <ACCOUNTS />
  <PROJ_TYPES />
  <PARAMS />
  <NAME_OBJECTS />
  <LITERALS />
  <VALUES />
  <REPORTS />
  <GROUPS />
  <CONTEXTS />
  <SUBTOTALS />
  <MACROS />
  <ASSIGNS />
  <UP_SETTINGS>
    <NUM_ANNUAL_STMTS>0</NUM_ANNUAL_STMTS>
    <NUM_INTERIM_STMTS>0</NUM_INTERIM_STMTS>
    <NUM_COMBINED_STMTS>0</NUM_COMBINED_STMTS>
    <NUM_LTP_STMTS>0</NUM_LTP_STMTS>
    <NUM_STP_STMTS>0</NUM_STP_STMTS>
    <NUM_COMBINED_PROJ_STMTS>0</NUM_COMBINED_PROJ_STMTS>
    <UP_ROUNDING>0</UP_ROUNDING>
    <UP_USE_HIDDEN_STMTS>False</UP_USE_HIDDEN_STMTS>
    <UP_INCLUDE_RC>False</UP_INCLUDE_RC>
    <UP_FORCE_RECALC>False</UP_FORCE_RECALC>
    <UP_RUNIFRCFAIL>False</UP_RUNIFRCFAIL>
    <UP_DELETEONFAILURE>False</UP_DELETEONFAILURE>
    <UP_INCLUDEPEERANALYSIS>False</UP_INCLUDEPEERANALYSIS>
    <UP_INCLUDECONSOLIDATEDINUP>False</UP_INCLUDECONSOLIDATEDINUP>
    <UP_RUNONSAVE>False</UP_RUNONSAVE>
  </UP_SETTINGS>
  <UP_CONDITIONS />
  <UP_KEYS />
  <UP_MAPPINGS />
  <INDUSTRY_CLASSIFICATION_SYSTEMS />
  <SENSITIVITY_PARAMETERS />
  <REQ_FIELDS />
  <PFPEXPORT_MAPPINGS />
  <PROJ_TYPE_HISTORY />
  <RMA_MAPPINGS />
  <RA_MAPPINGS />
  <RMA_CONDITIONS />
  <ORG_MACROS>
    <ORG_MACRO Name="DSCR (PV2)" Id="1" Release="true" IncludeInGcf="true" Type="false">
      <Expression><![CDATA[MacroValue=FE.MACRO(M.UT_ANTES_IMPTO_DEPR_AMORT_INT_GSTO_MAS_PCPLP)]]></Expression>
    </ORG_MACRO>
  </ORG_MACROS>
</MODEL>